# Need Travis to do the following
# - Have a copy of docker running
# - Build our image using Dockerfile.dev
# - Tell Travis how to run our test suite
# - Tell Travis how to deploy our code to AWS

# React CI info: https://create-react-app.dev/docs/running-tests/#continuous-integration
# Docker environment variable info: https://docs.docker.com/engine/reference/run/#env-environment-variables

sudo: required
language: generic

services:
 - docker

before_install:
 - docker build -t qpham01/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true qpham01/docker-react npm run test